/* previews.jsx — designed mini board renders for all 24 games (theme-aware).
   Shared by Game Cards + App Screens + Game Screens.
   BoardPreview({ game, size, gap, t }) — t = theme tokens (default dark).
   Needs brandkit (TOKENS,FONTS) + icons (Icon). Exports window.BoardPreview. */
const _C = TOKENS.cyan, _V = TOKENS.violet, _G = TOKENS.gold, _E = TOKENS.easy, _M = TOKENS.medium, _H = TOKENS.hard;

function MiniSun({ s = 14 }) { return <svg width={s} height={s} viewBox="0 0 20 20"><circle cx="10" cy="10" r="5.5" fill={_G} /></svg>; }
function MiniMoon({ s = 14 }) { return <svg width={s} height={s} viewBox="0 0 20 20"><path d="M14 4 C 9 4, 6 6.5, 6 10 C 6 13.5, 9 16, 14 16 C 10.5 13, 10.5 7, 14 4 Z" fill={_V} /></svg>; }

function BoardPreview({ game, size = 20, gap = 3, t }) {
  const T = t || TOKENS.theme.dark;
  const clue = T.key === 'dark' ? '#1A1D24' : T.key === 'paper' ? '#DACFB4' : '#DCE0E6';
  const card = T.key === 'dark' ? '#2A2E37' : T.surf2;
  const Txt = ({ children, fs, color, w = 700 }) => <span style={{ fontFamily: FONTS.display, fontWeight: w, fontSize: fs * 0.5, color: color || T.text, lineHeight: 1 }}>{children}</span>;
  const g = (cols, rows, sz, gp, fn) => <div style={{ display: 'grid', gridTemplateColumns: `repeat(${cols}, ${sz}px)`, gap: gp }}>
    {Array.from({ length: cols * rows }).map((_, i) => { const r = (i / cols) | 0, c = i % cols, o = fn(r, c, i) || []; return <div key={i} style={{ width: sz, height: sz, borderRadius: Math.max(3, sz * 0.22), background: o[0] || T.bg, border: `1px solid ${T.border}`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>{o[1]}</div>; })}
  </div>;
  const dot = (col, d) => <div style={{ width: d || size * 0.55, height: d || size * 0.55, borderRadius: '50%', background: col }} />;
  switch (game) {
    case 'tango': { const m = [[1,0,2,0,1],[0,2,0,1,0],[2,0,1,0,2],[0,1,0,2,0],[1,0,2,0,1]]; return g(5,5,size,gap,(r,c)=>[null, m[r][c]===1?<MiniSun s={size*0.62}/>:m[r][c]===2?<MiniMoon s={size*0.62}/>:null]); }
    case 'queens': { const reg=[[0,0,1,1,2],[0,0,1,2,2],[3,0,1,1,2],[3,3,4,1,2],[3,4,4,4,2]]; const dk=['#3a2e1e','#2a3550','#3a2540','#243a2e','#3a2430']; const lt=['#efe6d2','#dce6f2','#ecdcf2','#dcefe2','#f2dce2']; const cols=T.key==='dark'?dk:lt; const cr={'0-0':1,'2-2':1,'4-4':1}; return g(5,5,size,gap,(r,c)=>[cols[reg[r][c]], cr[r+'-'+c]?<Icon name="crown" size={size*0.6} color={_V} stroke={2.4}/>:null]); }
    case 'sudoku': { const m=[[5,'','',2,'',''],['','',6,'',3,''],['',1,'','','',4],[2,'','','',5,''],['',4,'',1,'',''],['','',3,'','',6]]; return g(6,6,size,gap,(r,c)=>[null, m[r][c]!==''?<Txt fs={size}>{m[r][c]}</Txt>:null]); }
    case 'flow': { const d={'0-0':_C,'0-4':_H,'2-1':_G,'4-4':_C,'4-0':_H,'2-3':_G}; const p={'1-0':_C,'2-0':_C,'3-0':_C,'4-1':_C,'4-2':_C,'4-3':_C,'1-4':_H}; return g(5,5,size,gap,(r,c)=>{const k=r+'-'+c; return [p[k]?p[k]+'33':null, d[k]?dot(d[k]):null];}); }
    case 'memory': { const rev={'0-1':['bolt',_G],'1-3':['spark',_C],'2-0':['star',_V],'3-2':['bolt',_G]}; return g(4,4,size,gap,(r,c)=>{const k=rev[r+'-'+c]; return [k?T.bg:card, k?<Icon name={k[0]} size={size*0.55} color={k[1]} stroke={2} fill={k[0]==='star'}/>:null];}); }
    case 'zip': { const n={'0-0':1,'0-4':2,'2-2':3,'4-0':4,'4-4':5}; return g(5,5,size,gap,(r,c)=>{const v=n[r+'-'+c]; return [v?_C+'22':null, v?<Txt fs={size} color={_C}>{v}</Txt>:null];}); }
    case 'kakuro': return g(5,5,size,gap,(r,c)=>{ const cl=r===0||c===0; return [cl?clue:null, cl&&(r+c)%2?<Txt fs={size*0.8} color={T.muted}>{((r*3+c*4)%9)+1}</Txt>:null]; });
    case 'logicpath': { const path=new Set(['0-0','1-0','2-0','2-1','2-2','3-2','4-2','4-3','4-4']); return g(5,5,size,gap,(r,c)=>{const k=r+'-'+c; const end=k==='0-0'||k==='4-4'; return [path.has(k)?_C+'2e':null, end?dot(k==='0-0'?_C:_G, size*0.5):null];}); }
    case 'lightup': { const wall={'1-1':2,'3-3':1}; const bulb=new Set(['0-3','2-0','4-4']); return g(5,5,size,gap,(r,c)=>{const k=r+'-'+c; if(wall[k]!==undefined) return [clue, <Txt fs={size*0.8} color={_H}>{wall[k]}</Txt>]; if(bulb.has(k)) return [_G+'22', dot(_G,size*0.5)]; return [null,null];}); }
    case 'nonogram': { const fill=new Set(['0-1','0-2','1-0','1-3','2-0','2-3','3-1','3-2','4-2']); return g(5,5,size,gap,(r,c)=>[fill.has(r+'-'+c)?_C:null,null]); }
    case 'patternmatch': return <div style={{ display:'flex', gap, alignItems:'center' }}>{['3','6','12','?'].map((v,i)=><div key={i} style={{ width:size*1.3, height:size*1.3, borderRadius:size*0.3, background:i===3?'transparent':card, border:`1.5px ${i===3?'dashed':'solid'} ${i===3?_C:T.border}`, display:'flex', alignItems:'center', justifyContent:'center' }}><Txt fs={size} color={i===3?_C:T.text}>{v}</Txt></div>)}</div>;
    case 'patches': { const pal=[_C,_V,_G,_E,_H,_M]; const map=[[0,0,1,2,2],[0,3,3,2,4],[5,3,1,1,4],[5,5,1,4,4],[5,0,0,0,4]]; return g(5,5,size,gap,(r,c)=>[pal[map[r][c]]+'cc',null]); }
    case '2048': { const m=[[2,4,'',''],['',8,16,''],['','',8,32],[2,'',4,64]]; const col={2:card,4:_C+'55',8:_G+'66',16:_V+'66',32:_M+'77',64:_H+'77'}; return g(4,4,size,gap,(r,c)=>{const v=m[r][c]; return [v?col[v]:null, v?<Txt fs={size*0.78}>{v}</Txt>:null];}); }
    case 'gravity': { const cols=[[_C,_G,_V,_H],[_G,_C,_H],[_V,_H,_C,_G,_C],[_H,_C],[_G,_V]]; return <div style={{ display:'flex', gap:gap*1.6, alignItems:'flex-end' }}>{cols.map((col,ci)=><div key={ci} style={{ width:size, background:card, borderRadius:size*0.4, padding:gap, display:'flex', flexDirection:'column', gap:gap, justifyContent:'flex-end', height:size*5.6 }}>{col.map((cc,i)=><div key={i} style={{ width:size*0.7, height:size*0.7, borderRadius:'50%', background:cc, margin:'0 auto' }} />)}</div>)}</div>; }
    case 'hexmerge': { const rows=[[2,4,2],[4,8,4,2],[2,4,2]]; return <div style={{ display:'flex', flexDirection:'column', gap }}>{rows.map((row,ri)=><div key={ri} style={{ display:'flex', gap, marginLeft:ri===1?0:size*0.55 }}>{row.map((v,i)=><div key={i} style={{ width:size*1.05, height:size*1.05, clipPath:'polygon(50% 0,100% 25%,100% 75%,50% 100%,0 75%,0 25%)', background:v>=8?_G+'88':v>=4?_C+'66':card, display:'flex', alignItems:'center', justifyContent:'center' }}><Txt fs={size*0.7}>{v}</Txt></div>)}</div>)}</div>; }
    case 'wordsling': { const m=[['M','I','N','D'],['T','A','E','S'],['R','O','L','P'],['G','N','I','K']]; const hot=new Set(['0-0','0-1','0-2','0-3']); return g(4,4,size,gap,(r,c)=>[hot.has(r+'-'+c)?_G+'cc':card, <Txt fs={size*0.62} color={hot.has(r+'-'+c)?'#0B0C0F':T.muted}>{m[r][c]}</Txt>]); }
    case 'hearts': return <div style={{ display:'flex' }}>{[0,1,2,3].map(i=><div key={i} style={{ width:size*1.7, height:size*2.4, borderRadius:size*0.3, background:card, border:`1px solid ${T.border}`, marginLeft:i?-size*0.5:0, display:'flex', alignItems:'center', justifyContent:'center', transform:`rotate(${(i-1.5)*6}deg)` }}><svg width={size} height={size} viewBox="0 0 20 20"><path d="M10 16 C 3 11, 3 5, 7 6 C 9 6.4, 10 8, 10 8.6 C 10 8, 11 6.4, 13 6 C 17 5, 17 11, 10 16 Z" fill={_H}/></svg></div>)}</div>;
    case 'solitaire': return <div style={{ display:'flex', gap:gap*1.4, alignItems:'flex-start' }}>{[2,3,1,2].map((cnt,ci)=><div key={ci} style={{ position:'relative', width:size*1.5, height:size*3.2 }}>{Array.from({length:cnt}).map((_,i)=><div key={i} style={{ position:'absolute', top:i*size*0.55, left:0, width:size*1.5, height:size*2, borderRadius:size*0.25, background:card, border:`1px solid ${T.border}` }}><div style={{ padding:2 }}><svg width={size*0.6} height={size*0.6} viewBox="0 0 20 20"><path d="M10 16 C 3 11, 3 5, 7 6 C 9 6.4, 10 8, 10 8.6 C 10 8, 11 6.4, 13 6 C 17 5, 17 11, 10 16 Z" fill={ci%2?_H:_C}/></svg></div></div>)}</div>)}</div>;
    case 'minesweeper': { const m=[[1,'','f',2,''],['',2,3,'','f'],[1,'','','',1],['','f',2,'',''],[1,2,'','',3]]; const nc={1:_C,2:_E,3:_H}; return g(5,5,size,gap,(r,c)=>{const v=m[r][c]; if(v==='f') return [card, <div style={{ width:size*0.4, height:size*0.4, background:_H, clipPath:'polygon(0 0,100% 35%,0 60%)' }} />]; if(v==='') return [card,null]; return [T.bg, <Txt fs={size*0.62} color={nc[v]}>{v}</Txt>];}); }
    case 'wordclimb': { const words=['DOG','COG','COT','CAT']; return <div style={{ display:'flex', flexDirection:'column', gap }}>{words.map((w,ri)=><div key={ri} style={{ display:'flex', gap, marginLeft:(3-ri)*size*0.4 }}>{w.split('').map((ch,i)=><div key={i} style={{ width:size*1.1, height:size*1.1, borderRadius:size*0.25, background:_E+(ri===0?'cc':'55'), display:'flex', alignItems:'center', justifyContent:'center' }}><Txt fs={size*0.58} color={ri===0?'#0B0C0F':T.text}>{ch}</Txt></div>)}</div>)}</div>; }
    case 'pinpoint': return <div style={{ display:'flex', gap:gap*2, alignItems:'center' }}><div style={{ display:'flex', flexDirection:'column', gap }}>{['Movies','Action','Sci-Fi','?'].map((s,i)=><div key={i} style={{ width:size*4, height:size*0.95, borderRadius:size*0.25, background:i===3?'transparent':card, border:`1px ${i===3?'dashed':'solid'} ${i===3?_C:T.border}`, display:'flex', alignItems:'center', paddingLeft:6 }}><span style={{ fontFamily:FONTS.body, fontSize:size*0.42, color:i===3?_C:T.muted, fontWeight:600 }}>{s}</span></div>)}</div><svg width={size*2.6} height={size*2.6} viewBox="0 0 40 40"><circle cx="20" cy="20" r="16" fill="none" stroke={_C} strokeWidth="2.5"/><circle cx="20" cy="20" r="8" fill="none" stroke={_C} strokeWidth="2.5"/><circle cx="20" cy="20" r="3" fill={_G}/></svg></div>;
    case 'namecountry': return <div style={{ display:'flex', alignItems:'center', gap:gap*2 }}><div style={{ width:size*0.3, height:size*4, background:T.muted, borderRadius:2 }} /><div style={{ borderRadius:size*0.2, overflow:'hidden', border:`1px solid ${T.border}` }}>{[_C,'#E8EDF2',_E].map((c,i)=><div key={i} style={{ width:size*3.6, height:size*1, background:c }} />)}</div><Txt fs={size*1.2} color={_C}>?</Txt></div>;
    case 'namecity': { const hs=[2.2,3.4,1.6,4,2.8,3.2,1.8]; const cols=[_C,_V,_G,_C,_M,_V,_C]; return <div style={{ display:'flex', alignItems:'flex-end', gap:gap*1.4, height:size*5 }}>{hs.map((h,i)=><div key={i} style={{ width:size*0.9, height:size*h, background:cols[i]+'cc', borderRadius:`${size*0.2}px ${size*0.2}px 0 0` }} />)}<Txt fs={size*1.1} color={_G}>?</Txt></div>; }
    default: return g(5,5,size,gap,()=>[null,null]);
  }
}
Object.assign(window, { BoardPreview, MiniSun, MiniMoon });
